# Stage 1: Build the application
FROM golang:1.23-alpine AS build

WORKDIR /app

COPY go.mod go.sum ./

# Download and cache dependencies
RUN go mod download

COPY . .

# Build the application
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

COPY .env.production .env
# Expose port 8080 to the outside world
EXPOSE 8080

# Command to run the executable
CMD ["./main"]

