apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-go
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-go
  template:
    metadata:
      labels:
        app: api-go
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app: api-go
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: topology.kubernetes.io/zone
              labelSelector:
                matchLabels:
                  app: api-go
      containers:
      - name:  api-go
        image: farrasyakila/api-go-prod
        env:
          - name: APP_NAME
            valueFrom:
              secretKeyRef:
                key: APP_NAME
                name: api-go
          - name: APP_PORT
            valueFrom:
              secretKeyRef:
                key: APP_PORT
                name: api-go
          - name: APP_ENV
            valueFrom:
              secretKeyRef:
                key: APP_ENV
                name: api-go
          - name: APP_VERSION
            valueFrom:
              secretKeyRef:
                key: APP_VERSION
                name: api-go
        resources:
          limits:
            cpu: "0.5"
            memory: 800Mi
          requests:
            cpu: "0.1"
            memory: 150Mi
        ports:
        - containerPort: 8080